steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/qlend-cron-job:$SHORT_SHA", "."]
    waitFor: ['-']
    id: 'build-image'
tags: ['cloud-builders-community']
images: ["gcr.io/$PROJECT_ID/qlend-cron-job"]
options:
  logging: CLOUD_LOGGING_ONLY
