apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: qlend-cron-job
spec:
  schedule: "0 1 */1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: qlend-cron-job
              # if version update, should change the image sha
              image: gcr.io/qlend-329115/qlend-cron-job:a19a058
              imagePullPolicy: Always
          restartPolicy: OnFailure
